app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questionnaire.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

app/questionnaire/urls.py
from django.urls import path

from . import views


app_name = 'questionnaire'
urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'set_page/<int:set_id>/',
        views.set_page,
        name='set_page'
    ),
    path(
        'passing_test/<int:num_set>/<int:num_test>/',
        views.passing_test,
        name='passing_test'
    ),
    path(
        'get_answer/<int:num_set>/<int:num_test>/',
        views.get_answer,
        name='get_answer'
    ),
    path(
        'show_result/<int:num_set>/',
        views.show_result,
        name='show_result'
    ),
]

app/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView)

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

app/core/models.py
from django.db import models

# Create your models here.

app/questionnaire/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class SetOfTests(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название теста'
    )
    description = models.TextField(
        verbose_name='Описание теста'
    )
    has_multiple_answers = models.BooleanField(
        default=False,
        verbose_name='Множественный выбор ответов')

    def __str__(self) -> str:
        return self.title


class Test(models.Model):
    number = models.IntegerField()
    text = models.TextField(
        verbose_name='Текст вопроса'
    )
    set_of_tests = models.ForeignKey(
        SetOfTests,
        on_delete=models.CASCADE,
        verbose_name='Набор тестов',
        related_name='set'
    )

    class Meta:
        unique_together = ('number', 'set_of_tests')

    def __str__(self) -> str:
        return self.text


class Answer(models.Model):
    text = models.TextField(
        verbose_name='Текст ответа'
    )
    test = models.ForeignKey(
        Test,
        on_delete=models.CASCADE
    )
    is_rigth = models.BooleanField()


class UserResults(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    set_of_tests = models.ForeignKey(
        SetOfTests,
        on_delete=models.CASCADE,
        related_name='results'
    )
    count_correct_answer = models.IntegerField(
        default=0
    )

app/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

app/core/views.py
from django.shortcuts import render

# Create your views here.

app/questionnaire/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from .models import SetOfTests, Test, Answer, UserResults


def index(request):
    """Главная страница со списком тестов."""
    set_of_tests = SetOfTests.objects.annotate(count_tests=Count('set__id'))
    context = {
        'sets': set_of_tests,
    }
    return render(request, 'questionnaire/index.html', context=context)


@login_required
def set_page(request, set_id):
    """Страница с отдельным тестом и его описанием."""
    set = get_object_or_404(SetOfTests, pk=set_id)
    cnt_tests = Test.objects.filter(set_of_tests=set).count()
    result = UserResults.objects.get_or_create(
        user=request.user,
        set_of_tests=set
    )[0].count_correct_answer

    context = {
        'set': set,
        'result': result,
        'cnt_tests': cnt_tests
    }
    return render(request, 'questionnaire/set_page.html', context=context)


@login_required
def passing_test(request, num_set, num_test):
    """Страница с вопросом теста и вариантами ответов."""
    if num_test == 1:
        obj = UserResults.objects.get(
            user=request.user,
            set_of_tests=num_set
        )
        obj.count_correct_answer = 0
        obj.save()

    has_multiple_answers = SetOfTests.objects.get(pk=num_set).has_multiple_answers
    question = Test.objects.get(
        set_of_tests=num_set,
        number=num_test
    )
    answers = Answer.objects.filter(test=question)

    context = {
        'question': question,
        'num_set': num_set,
        'answers': answers,
        'has_multiple_answers': has_multiple_answers,
    }
    return render(
        request,
        'questionnaire/passing_test.html',
        context=context
    )


@login_required
def get_answer(request, num_set, num_test):
    """Механизм принятия ответа и проверки его корректности"""
    tests = Test.objects.filter(set_of_tests=num_set)
    cnt_tests = tests.count()
    test = tests.get(number=num_test)
    cnt_right_answers = Answer.objects.filter(test=test, is_rigth=True).count()

    try:
        answers = Answer.objects.filter(pk__in=request.POST.getlist('choice'))
    except (KeyError, Answer.DoesNotExist):
        return passing_test(request, num_set, num_test)
    else:
        if (answers.filter(is_rigth=True).count()
            == answers.count()
            == cnt_right_answers
        ):
            tmp_res = UserResults.objects.get(
                user=request.user,
                set_of_tests=num_set
            )
            tmp_res.count_correct_answer += 1
            tmp_res.save()

    if num_test < cnt_tests:
        return redirect(f'/passing_test/{num_set}/{num_test + 1}/')
    return redirect(f'/show_result/{num_set}/')


@login_required
def show_result(request, num_set):
    """Страница с результатами теста"""
    cnt_correct_answers = UserResults.objects.get(
        user=request.user,
        set_of_tests=num_set
    ).count_correct_answer
    cnt_test = Test.objects.filter(
        set_of_tests=num_set
    ).aggregate(Count('id'))['id__count']
    result = round(cnt_correct_answers / cnt_test, 2) * 100

    context = {
        'count_correct_answers': cnt_correct_answers,
        'count_tests': cnt_test,
        'result': result
    }
    return render(request, 'questionnaire/result.html', context=context)

app/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('questionnaire:index')
    template_name = 'users/signup.html'

app/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
    <title>{% block title %}Тесты{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% block content %}Контент не подвезли :((({% endblock %}
    </main>
  </body>
</html>

app/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'questionnaire:index' %}">Тесты</a>
       <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% with request.resolver_match.view_name as view_name %}
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == 'users:logout' %}
            active
          {% endif %}
          "
          href="{% url 'users:logout' %}"
          >
            Выйти
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link">
            Пользователь: {{ user.username }}
          </a>
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == 'users:login' %}
            active
          {% endif %}"
          href="{% url 'users:login' %}"
          >
            Войти
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == 'users:signup' %}
            active
          {% endif %}"
          href="{% url 'users:signup' %}"
          >
            Регистрация
          </a>
        </li> 
        {% endif %}
        {% endwith %}
      </ul> 
    </div>
  </nav>      
</header>

app/templates/questionnaire/index.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
  <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Название</th>
          <th scope="col">Количество вопросов</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for set in sets %}
        <tr>
          <th scope="row">{{ set.pk }}</th>
          <td>{{ set.title }}</td>
          <td>{{ set.count_tests }}</td>
          <td>
            <a href="{% url 'questionnaire:set_page' set.pk %}">Пройти</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
  </table>
</div>
{% endblock %}

app/templates/questionnaire/passing_test.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<h3>
    <p>Вопрос № {{ question.number }}</p>
</h3>
<h2>
    <p>{{ question.text }}</p>
</h2>

<form action="{% url 'questionnaire:get_answer' num_set question.number %}" method="post">
    {% csrf_token %}
    {% for answer in answers %}
        <div class="form-check">
            <input class="form-check-input" 
            {% if has_multiple_answers %}
                type="checkbox" 
            {% else %}
                type="radio" 
            {% endif %}            
            name="choice" id="choice{{ forloop.counter }}" value="{{ answer.pk }}" />
            <label class="form-check-label" for="choice{{ forloop.counter }}">{{ answer.text }}</label>
            <br/>
        </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">
        Далее
    </button>
</form>
</div>
{% endblock %}

app/templates/questionnaire/result.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<h3>
    <p>Ваш результат: {{ result }}%</p>
</h3>
<h2>
    {% if count_correct_answers == 1%}
        <p>{{ count_correct_answers }} правильный ответ из {{ count_tests }}</p>
    {% else %}
        <p>{{ count_correct_answers }} правильных ответов из {{ count_tests }}</p>
    {% endif %}
</h2>

<a href="{% url 'questionnaire:index' %}">Вернуться на главную</a>
</div>
{% endblock %}

app/templates/questionnaire/set_page.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<h3>
    <p>{{ set.title }}</p>
</h3>
<p>
    {{ set.description }}
</p>
<p>
    {% if result == 1 %}
        Ваш прошлый результат: {{ result }} правильный ответ из {{ cnt_tests }}
    {% else %}
        Ваш прошлый результат: {{ result }} правильных ответов из {{ cnt_tests }}
    {% endif %}
</p>
<a class="btn btn-primary" href="{% url 'questionnaire:passing_test' set.pk 1%}" role="button">Начать</a>
</div>
{% endblock %}

app/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
    <a href="{% url 'questionnaire:index' %}">Вернуться на главную</a>
  </div> <!-- col -->
</div> <!-- row -->

{% endblock %} 

app/templates/users/login.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-sm-4 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-sm-4 offset-md-5">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

app/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-sm-6 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% comment %} {% load user_filters %} {# Загружаем фильтры #} {% endcomment %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                  {% comment %} {{ field }} {% endcomment %}
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-5">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}